# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18fc00712b4e81cc2e5770d8b3feabbc6cb10b40aaca1ebadf861f5f467f514d2aa16fa87ddda2f3c6b8eaf07c1962f375f7d1ec1408f18b2f1c049cf19cf67d

test:
  secret_key_base: ff5c0c27de1dcc134e3c64f76cdefdb933e08c6881a01089577d69e0da387ef03b4f6376d087f2b35d84c4dcbbe05ce56c1e1636b6c7f8ff4ac6b68d9ff8304f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
